update_fastlane
default_platform(:ios)

platform :ios do
	desc "Build and distribute app to Firebase App Distribution"
	lane :distribute do
		# Get API key
        api_key = app_store_connect_api_key(key_id: "", issuer_id: "", key_filepath: "")
		setup_ci()
		# Sync certificates and profiles
        match(
            type: "development",
            readonly: false,
            app_identifier: ENV["APP_BUNDLE_ID"],
            api_key: api_key
        )
        # Build and sign iOS app
        build_ios_app(
            scheme: "OfficeSports",
            clean: true,
            output_directory: "build",
            output_name: "OfficeSports.ipa",
            export_method: "development"
        )
        # Distribute to Firebase
        firebase_app_distribution(
            app: ENV["FB_APP_ID"],
            firebase_cli_token: ENV["FB_CLI_TOKEN"],
            groups: "internal-testers"
        )
	end
end
