name: Validate and publish functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm i --legacy-peer-deps --prefix functions

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        run: npm run deploy
        working-directory: functions
